title: Param Thakkar
description: I'm an enthusiastic student who likes to tinker with computers, and this site is sorta like a showcase of my projects and achievements.
url: https://www.param.me
sass:
  style: compressed

links:
  github: paramt
  email: contact@param.me
  linkedin: paramt
  twitter: paramoham
  instagram: xparam
  discord: 422072307146686464

status:
  song: Confetti - Ghost
  song-link: https://www.youtube.com/watch?v=mgQOEPWxp7c
  game: Hollow Knight
  working-on: College apps
