title: Param Thakkar
description: I'm an enthusiastic student who likes to tinker with computers, and this site is sorta like a showcase of my projects and achievements.

links:
  github: paramt
  email: contact@param.me
  linkedin: paramt
  twitter: paramoham
  instagram: xparam
  patreon: paramt
